# Generated by Django 5.1.15 on 2026-09-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_billing_address_customer_credit_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='state_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
