# Generated by Django 5.1.15 on 2026-09-30 19:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_state_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMRPPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('rate_per_piece', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mrp_pricings', to='customers.customer')),
            ],
            options={
                'ordering': ['mrp'],
                'constraints': [models.UniqueConstraint(fields=('customer', 'mrp'), name='unique_customer_mrp_pricing')],
            },
        ),
    ]
