from django.urls import path

from .views import (
    AuditLogListView,
    BusinessProfileView,
    CreditNoteDetailView,
    CreditNoteListCreateView,
    InvoiceAmendView,
    InvoiceCorrectionEligibilityView,
    InvoiceDetailView,
    InvoiceDraftUpdateView,
    InvoiceListCreateView,
    InvoicePdfView,
    PaymentDetailView,
    PaymentListCreateView,
    InvoiceCancelView,
    PaymentReverseView,
    InvoiceDraftCreateView,
    InvoicePostView,
)
from .reporting import DailySalesReportView, ProfitLossReportView, StockValuationReportView, TopProductsReportView
from .reports import (
    CustomerSalesReportView,
    DashboardReportView,
    InventoryValuationReportView,
    ProductSalesReportView,
    ProfitReportView,
    PurchaseSummaryReportView,
    SalesSummaryReportView,
    StockMovementReportView,
    TaxSummaryReportView,
)

urlpatterns = [
    path("business-profile/", BusinessProfileView.as_view(), name="business-profile"),
    path("audit-logs/", AuditLogListView.as_view(), name="audit-log-list"),
    path("invoices/", InvoiceListCreateView.as_view(), name="invoice-list-create"),
    path("invoices/drafts/", InvoiceDraftCreateView.as_view(), name="invoice-draft-create"),
    path("invoices/<int:pk>/", InvoiceDetailView.as_view(), name="invoice-detail"),
    path("invoices/<int:pk>/draft/", InvoiceDraftUpdateView.as_view(), name="invoice-draft-update"),
    path("invoices/<int:pk>/post/", InvoicePostView.as_view(), name="invoice-post"),
    path("invoices/<int:pk>/pdf/", InvoicePdfView.as_view(), name="invoice-pdf"),
    path("invoices/<int:pk>/cancel/", InvoiceCancelView.as_view(), name="invoice-cancel"),
    path("invoices/<int:pk>/correction-eligibility/", InvoiceCorrectionEligibilityView.as_view(), name="invoice-correction-eligibility"),
    path("invoices/<int:pk>/amend/", InvoiceAmendView.as_view(), name="invoice-amend"),
    path("credit-notes/", CreditNoteListCreateView.as_view(), name="credit-note-list-create"),
    path("credit-notes/<int:pk>/", CreditNoteDetailView.as_view(), name="credit-note-detail"),
    path("payments/", PaymentListCreateView.as_view(), name="payment-list-create"),
    path("payments/<int:pk>/", PaymentDetailView.as_view(), name="payment-detail"),
    path("payments/<int:pk>/reverse/", PaymentReverseView.as_view(), name="payment-reverse"),
    path("reports/daily-sales/", DailySalesReportView.as_view(), name="daily-sales-report"),
    path("reports/stock-valuation/", StockValuationReportView.as_view(), name="stock-valuation-report"),
    path("reports/profit-loss/", ProfitLossReportView.as_view(), name="profit-loss-report"),
    path("reports/top-products/", TopProductsReportView.as_view(), name="top-products-report"),
    path("reports/sales/", SalesSummaryReportView.as_view(), name="sales-report"),
    path("reports/purchases/", PurchaseSummaryReportView.as_view(), name="purchases-report"),
    path("reports/inventory/", InventoryValuationReportView.as_view(), name="inventory-report"),
    path("reports/stock-movement/", StockMovementReportView.as_view(), name="stock-movement-report"),
    path("reports/products/", ProductSalesReportView.as_view(), name="products-report"),
    path("reports/customers/", CustomerSalesReportView.as_view(), name="customers-report"),
    path("reports/tax/", TaxSummaryReportView.as_view(), name="tax-report"),
    path("reports/profit/", ProfitReportView.as_view(), name="profit-report"),
    path("reports/dashboard/", DashboardReportView.as_view(), name="dashboard-report"),
]
