# Generated by Django 5.1.15 on 2026-09-08 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoice_cancellation_reason_invoice_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceIdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='idempotency_record', to='billing.invoice')),
            ],
        ),
    ]
