# Generated by Django 5.1.15 on 2026-09-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_invoice_billing_address_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceidempotencykey',
            name='request_hash',
            field=models.CharField(default='', max_length=64),
        ),
    ]
