# Generated by Django 5.1.15 on 2026-09-08 19:09

from decimal import Decimal
from django.db import migrations, models

def split_legacy_tax(apps, schema_editor):
    from decimal import Decimal
    InvoiceLineItem = apps.get_model('billing', 'InvoiceLineItem')
    for item in InvoiceLineItem.objects.all():
        if item.tax_amount:
            half = (item.tax_amount / Decimal('2.0')).quantize(Decimal('0.01'))
            item.cgst_amount = half
            item.sgst_amount = item.tax_amount - half
            item.cgst_rate = item.tax_rate / Decimal('2.0') if item.tax_rate else Decimal('0')
            item.sgst_rate = item.tax_rate / Decimal('2.0') if item.tax_rate else Decimal('0')
            item.save(update_fields=['cgst_amount', 'sgst_amount', 'cgst_rate', 'sgst_rate'])

    CreditNoteLineItem = apps.get_model('billing', 'CreditNoteLineItem')
    for item in CreditNoteLineItem.objects.all():
        if item.tax_amount:
            half = (item.tax_amount / Decimal('2.0')).quantize(Decimal('0.01'))
            item.cgst_amount = half
            item.sgst_amount = item.tax_amount - half
            item.cgst_rate = item.tax_rate / Decimal('2.0') if item.tax_rate else Decimal('0')
            item.sgst_rate = item.tax_rate / Decimal('2.0') if item.tax_rate else Decimal('0')
            item.save(update_fields=['cgst_amount', 'sgst_amount', 'cgst_rate', 'sgst_rate'])

class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_alter_payment_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('trade_name', models.CharField(blank=True, max_length=255)),
                ('gstin', models.CharField(max_length=25)),
                ('registered_address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=10)),
                ('contact_details', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='creditnotelineitem',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='creditnotelineitem',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='creditnotelineitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='creditnotelineitem',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='creditnotelineitem',
            name='igst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='creditnotelineitem',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='creditnotelineitem',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_registration_type_snapshot',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_state_code_snapshot',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_address_snapshot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_business_name_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_gstin_snapshot',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_state_code_snapshot',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_state_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_mode',
            field=models.CharField(choices=[('exclusive', 'Exclusive'), ('inclusive', 'Inclusive')], default='exclusive', max_length=10),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='igst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='creditnotelineitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.RunPython(split_legacy_tax, migrations.RunPython.noop),
    ]
