# Generated by Django 5.1.15 on 2026-09-15 07:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_invoicelineitem_sales_unit_conversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='terms_and_conditions',
            field=models.TextField(blank=True, default='Goods once sold will not be taken back or exchanged.\nBills not paid due date will attract 24% interest.'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='mrp_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
