# Generated by Django 5.1.15 on 2026-09-15 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_businessprofile_email_businessprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amended_from_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='replacement_invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='billing.invoice'),
        ),
    ]
