import { useEffect, useState } from 'react'
import api, { apiErrorMessage } from '../api/client'
import StatusMessage from '../components/StatusMessage'
import { useAuth } from '../context/AuthContext'

const emptyCustomer = { name: '', contact_info: '', customer_type: 'B2C', gstin: '', is_regular: false }
function rows(data) { return Array.isArray(data) ? data : data?.results || [] }
function money(value) { return `Rs ${Number(value || 0).toLocaleString('en-IN', { minimumFractionDigits: 2 })}` }

export default function CustomersPage() {
  const { user } = useAuth(); const isAdmin = user?.role === 'admin'
  const [customers, setCustomers] = useState([]); const [balances, setBalances] = useState({}); const [form, setForm] = useState(emptyCustomer); const [editing, setEditing] = useState(null); const [showForm, setShowForm] = useState(false); const [busy, setBusy] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  async function loadCustomers() { setBusy(true); setError(''); try { const list = rows((await api.get('/customers/')).data); setCustomers(list); const reports = await Promise.all(list.map(async (customer) => { try { const report = await api.get(`/customers/${customer.id}/report/`); return [customer.id, report.data.outstanding_balance] } catch { return [customer.id, null] } })); setBalances(Object.fromEntries(reports)) } catch (err) { setError(apiErrorMessage(err)) } finally { setBusy(false) } }
  useEffect(() => { loadCustomers() }, [])
  function beginCreate() { setEditing(null); setForm(emptyCustomer); setShowForm(true) }
  function beginEdit(customer) { setEditing(customer.id); setForm({ name: customer.name || '', contact_info: customer.contact_info || '', customer_type: customer.customer_type || 'B2C', gstin: customer.gstin || '', is_regular: Boolean(customer.is_regular) }); setShowForm(true) }
  function change(event) { const { name, value, type, checked } = event.target; setForm({ ...form, [name]: type === 'checkbox' ? checked : value }) }
  async function save(event) { event.preventDefault(); setSaving(true); setError(''); try { if (editing) await api.patch(`/customers/${editing}/`, form); else await api.post('/customers/', form); setShowForm(false); await loadCustomers() } catch (err) { setError(apiErrorMessage(err)) } finally { setSaving(false) } }
  async function remove(customer) { if (!window.confirm(`Delete ${customer.name}?`)) return; try { await api.delete(`/customers/${customer.id}/`); await loadCustomers() } catch (err) { setError(apiErrorMessage(err)) } }
  return <section className="page-section"><header className="page-header"><div><p className="eyebrow">Relationships / ledger</p><h1>Customers</h1><p className="page-subtitle">Registered accounts, tax identity, and outstanding balance.</p></div>{isAdmin && <button className="primary-button" onClick={beginCreate}>Add customer</button>}</header><StatusMessage>{error}</StatusMessage>{showForm && isAdmin && <form className="record-form" onSubmit={save}><div className="form-heading"><div><p className="eyebrow">{editing ? 'Edit record' : 'New record'}</p><h2>{editing ? 'Update customer' : 'Add customer'}</h2></div><button type="button" className="quiet-button" onClick={() => setShowForm(false)}>Close</button></div><div className="form-grid"><label>Name<input name="name" value={form.name} onChange={change} required /></label><label>Contact information<input name="contact_info" value={form.contact_info} onChange={change} /></label><label>Customer type<select name="customer_type" value={form.customer_type} onChange={change}><option value="B2C">B2C</option><option value="B2B">B2B</option></select></label><label>GSTIN<input name="gstin" value={form.gstin} onChange={change} /></label><label className="checkbox-label"><input type="checkbox" name="is_regular" checked={form.is_regular} onChange={change} /> Regular account</label></div><div className="form-actions"><button type="button" className="quiet-button" onClick={() => setShowForm(false)}>Cancel</button><button className="primary-button" disabled={saving}>{saving ? 'Saving...' : 'Save customer'}</button></div></form>}<div className="table-frame"><div className="table-meta"><span>{customers.length} customers</span><span className="table-note">Outstanding balances from customer reports</span></div>{busy ? <div className="empty-state">Loading customers...</div> : customers.length === 0 ? <div className="empty-state">No customers yet.</div> : <div className="table-scroll"><table><thead><tr><th>Customer</th><th>Type</th><th>GSTIN</th><th>Contact</th><th>Outstanding</th>{isAdmin && <th aria-label="Actions" />}</tr></thead><tbody>{customers.map((customer) => <tr key={customer.id}><td><strong>{customer.name}</strong><small>{customer.is_regular ? 'Regular account' : 'Occasional account'}</small></td><td><span className="type-chip">{customer.customer_type}</span></td><td>{customer.gstin || '-'}</td><td>{customer.contact_info || '-'}</td><td><span className={Number(balances[customer.id] || 0) > 0 ? 'balance due' : 'balance'}>{balances[customer.id] === null ? 'Unavailable' : money(balances[customer.id])}</span></td>{isAdmin && <td><div className="row-actions"><button className="text-button" onClick={() => beginEdit(customer)}>Edit</button><button className="text-button danger" onClick={() => remove(customer)}>Delete</button></div></td>}</tr>)}</tbody></table></div>}</div></section>
}
