# Generated by Django 5.1.15 on 2026-09-07 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('unit_type', models.CharField(choices=[('carton', 'Carton'), ('box', 'Box'), ('piece', 'Piece')], default='piece', max_length=20)),
                ('unit_conversion_factor', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_slab', models.PositiveIntegerField(choices=[(5, '5%'), (18, '18%'), (40, '40%')], default=18)),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('low_stock_threshold', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.DecimalField(decimal_places=3, max_digits=12)),
                ('movement_type', models.CharField(choices=[('in', 'In'), ('out', 'Out')], default='in', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='inventory.warehouse')),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'category', 'brand'], name='inventory_p_name_f89005_idx'),
        ),
    ]
