# Generated by Django 5.1.15 on 2026-09-08 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_balance_and_audit_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockledger',
            new_name='inventory_s_product_5bb941_idx',
            old_name='inventory_s_product__f3c0dc_idx',
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='quantity_change',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(-999999999)]),
        ),
    ]
