# Generated by Django 5.1.15 on 2026-09-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_backfill_average_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockledger',
            name='movement_type',
            field=models.CharField(choices=[('OPENING_STOCK', 'Opening Stock'), ('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('SALE_REVERSAL', 'Sale Reversal'), ('SALES_RETURN', 'Sales Return'), ('PURCHASE_RETURN', 'Purchase Return'), ('DAMAGE', 'Damage'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out')], default='ADJUSTMENT', max_length=20),
        ),
    ]
