# Generated by Django 5.1.15 on 2026-09-08 19:09

import django.db.models.deletion
from django.db import migrations, models

def seed_tax_rates(apps, schema_editor):
    TaxRate = apps.get_model('inventory', 'TaxRate')
    Product = apps.get_model('inventory', 'Product')
    tax_5, _ = TaxRate.objects.get_or_create(name='GST 5%', defaults={'rate': 5.0})
    tax_18, _ = TaxRate.objects.get_or_create(name='GST 18%', defaults={'rate': 18.0})
    tax_40, _ = TaxRate.objects.get_or_create(name='GST 40%', defaults={'rate': 40.0})
    mapping = {5: tax_5, 18: tax_18, 40: tax_40}
    for product in Product.objects.all():
        if product.tax_slab in mapping:
            product.tax = mapping[product.tax_slab]
            product.save(update_fields=['tax'])

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_stockledger_movement_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.taxrate'),
        ),
        migrations.RunPython(seed_tax_rates, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='product',
            name='tax_slab',
        ),
        migrations.AddField(
            model_name='product',
            name='hsn_sac',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='is_tax_applicable',
            field=models.BooleanField(default=True),
        ),
    ]
