# Generated by Django 5.1.15 on 2026-09-30 21:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_openingstocknumbercounter_alter_warehouse_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseTransferNumberCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy_code', models.CharField(max_length=10, unique=True)),
                ('last_serial', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='movement_type',
            field=models.CharField(choices=[('OPENING_STOCK', 'Opening Stock'), ('PURCHASE', 'Purchase'), ('PURCHASE_REVERSAL', 'Purchase Reversal'), ('SALE', 'Sale'), ('SALE_REVERSAL', 'Sale Reversal'), ('SALES_RETURN', 'Sales Return'), ('PURCHASE_RETURN', 'Purchase Return'), ('DAMAGE', 'Damage'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('STOCK_ADJUSTMENT_IN', 'Stock Adjustment In'), ('STOCK_ADJUSTMENT_OUT', 'Stock Adjustment Out'), ('WAREHOUSE_TRANSFER_IN', 'Warehouse Transfer In'), ('WAREHOUSE_TRANSFER_OUT', 'Warehouse Transfer Out')], default='ADJUSTMENT', max_length=30),
        ),
        migrations.CreateModel(
            name='WarehouseTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(max_length=50, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit', models.CharField(choices=[('piece', 'Piece'), ('master box', 'Master Box')], default='piece', max_length=50)),
                ('conversion_factor', models.DecimalField(decimal_places=3, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('base_quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_cost_snapshot', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('transfer_value', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reason', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_warehouse_transfers', to=settings.AUTH_USER_MODEL)),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='inventory.warehouse')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='inventory.product')),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseTransferIdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('request_hash', models.CharField(default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transfer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='idempotency_record', to='inventory.warehousetransfer')),
            ],
        ),
        migrations.AddIndex(
            model_name='warehousetransfer',
            index=models.Index(fields=['product', 'source_warehouse', '-effective_date'], name='inventory_w_product_d036c2_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousetransfer',
            index=models.Index(fields=['product', 'destination_warehouse', '-effective_date'], name='inventory_w_product_3eb71d_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousetransfer',
            index=models.Index(fields=['-effective_date'], name='inventory_w_effecti_bc1752_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousetransfer',
            index=models.Index(fields=['-created_at'], name='inventory_w_created_9e9cc3_idx'),
        ),
        migrations.AddConstraint(
            model_name='warehousetransfer',
            constraint=models.CheckConstraint(condition=models.Q(('source_warehouse', models.F('destination_warehouse')), _negated=True), name='different_transfer_warehouses'),
        ),
    ]
