# Generated by Django 5.1.15 on 2026-10-01 18:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_warehousetransfernumbercounter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPurchasePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('rate_per_piece', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_pricings', to='inventory.supplier')),
            ],
            options={
                'ordering': ['mrp'],
                'constraints': [models.UniqueConstraint(fields=('supplier', 'mrp'), name='unique_supplier_mrp_purchase_pricing')],
            },
        ),
    ]
